# Generated by Django 5.0.2 on 2025-03-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
