# Generated by Django 5.0.2 on 2025-03-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0002_alter_propuesta_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='cambioPropuesta',
            field=models.TextField(default=''),
        ),
    ]
