# Generated by Django 5.0.2 on 2025-03-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0004_version_usuario_alter_comentario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='votos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='version',
            name='votos',
            field=models.IntegerField(default=0),
        ),
    ]
