# Generated by Django 5.0.2 on 2025-03-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0006_remove_propuesta_votos_remove_version_votos_voto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='propuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='propuestas.propuesta'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='propuestas.version'),
        ),
    ]
