# Generated by Django 5.0.2 on 2025-03-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0007_alter_voto_propuesta_alter_voto_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='voto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='version',
            name='voto',
            field=models.IntegerField(default=0),
        ),
    ]
