# Generated by Django 5.0.2 on 2025-03-29 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0008_propuesta_voto_version_voto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='propuestas.version'),
        ),
        migrations.AddField(
            model_name='version',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='propuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='propuestas.propuesta'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas', to='propuestas.categoria'),
        ),
        migrations.AlterField(
            model_name='version',
            name='propuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='propuestas.propuesta'),
        ),
    ]
