# Generated by Django 5.0.2 on 2025-03-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0009_comentario_version_version_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='propuesta',
        ),
        migrations.RemoveField(
            model_name='version',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='version',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='propuesta',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='usuario',
        ),
        migrations.RenameField(
            model_name='propuesta',
            old_name='usuarioCreador',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='propuesta',
            old_name='voto',
            new_name='votos',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
        migrations.DeleteModel(
            name='Voto',
        ),
    ]
